-- ============================================================
-- Lu's Collections — Supabase Database Setup
-- Run this whole file once in Supabase SQL Editor.
-- ============================================================

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- Tables
-- ------------------------------------------------------------
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  category text not null,
  price integer not null check (price >= 0),
  old_price integer check (old_price is null or old_price >= 0),
  badge text default '',
  image text not null,
  description text default '',
  sizes jsonb not null default '[]'::jsonb,
  colors jsonb not null default '[]'::jsonb,
  stock integer not null default 0 check (stock >= 0),
  is_active boolean not null default true,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_no text unique not null,
  customer_name text not null,
  phone text not null,
  email text default '',
  address text not null,
  note text default '',
  payment_method text not null,
  payment_reference text default '',
  payment_status text not null default 'pending',
  order_status text not null default 'pending',
  subtotal integer not null,
  delivery_fee integer not null default 0,
  total integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  price integer not null,
  qty integer not null check (qty > 0),
  size text default '',
  color text default ''
);

create table if not exists public.settings (
  key text primary key,
  value text not null default ''
);

create index if not exists idx_products_category on public.products(category);
create index if not exists idx_products_active on public.products(is_active);
create index if not exists idx_orders_status on public.orders(order_status);
create index if not exists idx_orders_created_at on public.orders(created_at desc);

-- ------------------------------------------------------------
-- Admin helper
-- ------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.admin_users
    where id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- ------------------------------------------------------------
-- RLS
-- ------------------------------------------------------------
alter table public.products enable row level security;
alter table public.admin_users enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.settings enable row level security;

-- Products: customers can only read active products; admins can manage all.
drop policy if exists "public read active products" on public.products;
create policy "public read active products"
on public.products for select
to anon, authenticated
using (is_active = true or (select public.is_admin()));

drop policy if exists "admins insert products" on public.products;
create policy "admins insert products"
on public.products for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "admins update products" on public.products;
create policy "admins update products"
on public.products for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "admins delete products" on public.products;
create policy "admins delete products"
on public.products for delete
to authenticated
using ((select public.is_admin()));

grant select on public.products to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
grant insert, update, delete on public.products to authenticated;

drop policy if exists "admins can read admin_users" on public.admin_users;
create policy "admins can read admin_users"
on public.admin_users for select
to authenticated
using ((select public.is_admin()) or id = (select auth.uid()));

grant select on public.admin_users to authenticated;

-- Orders and order_items are NOT directly writable by browsers.
-- Customers place orders through the secure create_order() RPC below.
drop policy if exists "admins read orders" on public.orders;
create policy "admins read orders"
on public.orders for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "admins update orders" on public.orders;
create policy "admins update orders"
on public.orders for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

grant select, update on public.orders to authenticated;

drop policy if exists "admins read order items" on public.order_items;
create policy "admins read order items"
on public.order_items for select
to authenticated
using ((select public.is_admin()));

grant select on public.order_items to authenticated;

-- Settings: public can read store settings; only admins can edit them.
drop policy if exists "public read settings" on public.settings;
create policy "public read settings"
on public.settings for select
to anon, authenticated
using (true);

drop policy if exists "admins insert settings" on public.settings;
create policy "admins insert settings"
on public.settings for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "admins update settings" on public.settings;
create policy "admins update settings"
on public.settings for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

grant select on public.settings to anon, authenticated;
grant insert, update on public.settings to authenticated;

-- ------------------------------------------------------------
-- Secure order creation
-- ------------------------------------------------------------
create or replace function public.create_order(
  p_customer_name text,
  p_phone text,
  p_email text,
  p_address text,
  p_note text,
  p_payment_method text,
  p_payment_reference text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_subtotal integer := 0;
  v_delivery integer := 0;
  v_total integer := 0;
  v_order_id bigint;
  v_order_no text;
  item jsonb;
  v_product products%rowtype;
  v_qty integer;
  v_size text;
  v_color text;
  v_settings text;
begin
  if coalesce(trim(p_customer_name),'') = '' or coalesce(trim(p_phone),'') = '' or coalesce(trim(p_address),'') = '' then
    raise exception 'Name, phone and address are required';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Your cart is empty';
  end if;

  select value into v_settings from public.settings where key = 'delivery_fee';
  v_delivery := coalesce(nullif(v_settings,'')::integer, 0);

  for item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := greatest(1, coalesce((item->>'qty')::integer, 1));
    v_size := coalesce(item->>'size','');
    v_color := coalesce(item->>'color','');

    select * into v_product
    from public.products
    where id = (item->>'productId')::bigint
      and is_active = true
    for update;

    if not found then
      raise exception 'Product not found';
    end if;

    if v_product.stock < v_qty then
      raise exception '% is out of stock', v_product.name;
    end if;

    v_subtotal := v_subtotal + (v_product.price * v_qty);
  end loop;

  v_total := v_subtotal + v_delivery;
  v_order_no := 'LUS-' || to_char(now(),'YYYYMMDD') || '-' || upper(substr(encode(gen_random_bytes(4),'hex'),1,6));

  insert into public.orders(
    order_no, customer_name, phone, email, address, note,
    payment_method, payment_reference, subtotal, delivery_fee, total
  ) values (
    v_order_no, trim(p_customer_name), trim(p_phone), coalesce(trim(p_email),''),
    trim(p_address), coalesce(trim(p_note),''), trim(p_payment_method),
    coalesce(trim(p_payment_reference),''), v_subtotal, v_delivery, v_total
  ) returning id into v_order_id;

  for item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := greatest(1, coalesce((item->>'qty')::integer, 1));
    v_size := coalesce(item->>'size','');
    v_color := coalesce(item->>'color','');

    select * into v_product
    from public.products
    where id = (item->>'productId')::bigint
    for update;

    insert into public.order_items(order_id, product_id, product_name, price, qty, size, color)
    values(v_order_id, v_product.id, v_product.name, v_product.price, v_qty, v_size, v_color);

    update public.products
    set stock = stock - v_qty, updated_at = now()
    where id = v_product.id;
  end loop;

  return jsonb_build_object(
    'orderNo', v_order_no,
    'total', v_total,
    'subtotal', v_subtotal,
    'deliveryFee', v_delivery,
    'paymentMethod', p_payment_method,
    'status', 'pending'
  );
end;
$$;

revoke all on function public.create_order(text,text,text,text,text,text,text,jsonb) from public;
grant execute on function public.create_order(text,text,text,text,text,text,text,jsonb) to anon, authenticated;

-- ------------------------------------------------------------
-- Customer order lookup by order number + phone
-- ------------------------------------------------------------
create or replace function public.lookup_order(p_order_no text, p_phone text)
returns jsonb
language sql
security definer
set search_path = public
stable
as $$
  select coalesce(
    (
      select jsonb_build_object(
        'orderNo', o.order_no,
        'customerName', o.customer_name,
        'phone', o.phone,
        'paymentMethod', o.payment_method,
        'paymentStatus', o.payment_status,
        'orderStatus', o.order_status,
        'subtotal', o.subtotal,
        'deliveryFee', o.delivery_fee,
        'total', o.total,
        'createdAt', o.created_at,
        'items', coalesce((
          select jsonb_agg(jsonb_build_object(
            'productName', oi.product_name,
            'qty', oi.qty,
            'price', oi.price,
            'size', oi.size,
            'color', oi.color
          ) order by oi.id)
          from public.order_items oi where oi.order_id = o.id
        ), '[]'::jsonb)
      )
      from public.orders o
      where lower(o.order_no) = lower(trim(p_order_no))
        and regexp_replace(o.phone,'\\D','','g') = regexp_replace(trim(p_phone),'\\D','','g')
      limit 1
    ), '{}'::jsonb
  );
$$;

revoke all on function public.lookup_order(text,text) from public;
grant execute on function public.lookup_order(text,text) to anon, authenticated;

-- ------------------------------------------------------------
-- Storage bucket for product images
-- ------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('product-images','product-images',true)
on conflict (id) do update set public = true;

-- Public can view product images; only admins can upload/change/delete.
drop policy if exists "public read product images" on storage.objects;
create policy "public read product images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'product-images');

drop policy if exists "admins upload product images" on storage.objects;
create policy "admins upload product images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'product-images' and (select public.is_admin()));

drop policy if exists "admins update product images" on storage.objects;
create policy "admins update product images"
on storage.objects for update
to authenticated
using (bucket_id = 'product-images' and (select public.is_admin()))
with check (bucket_id = 'product-images' and (select public.is_admin()));

drop policy if exists "admins delete product images" on storage.objects;
create policy "admins delete product images"
on storage.objects for delete
to authenticated
using (bucket_id = 'product-images' and (select public.is_admin()));

-- ------------------------------------------------------------
-- Initial store settings
-- ------------------------------------------------------------
insert into public.settings(key,value) values
('shop_name','Lu''s Collections'),
('phone','09-XXXXXXXXX'),
('address','တောင်ကြီးမြို့၊ ရှမ်းပြည်နယ်။'),
('viber','#'),
('facebook','#'),
('tiktok','#'),
('kbzpay',''),
('wavepay',''),
('delivery_fee','0')
on conflict(key) do nothing;

-- ------------------------------------------------------------
-- Initial products
-- ------------------------------------------------------------
insert into public.products
(name,slug,category,price,old_price,badge,image,description,sizes,colors,stock,is_active,is_featured)
values
('Silk Sleepwear Set','silk-sleepwear-set','Sleepwear',32000,null,'NEW','https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=85&w=900&auto=format&fit=crop','Soft, elegant sleepwear designed for comfortable nights and relaxed mornings.','["S","M","L","XL"]','["Ivory","Rose"]',20,true,true),
('Casual Linen Blouse','casual-linen-blouse','Top & Blouse',28000,null,'NEW','https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=85&w=900&auto=format&fit=crop','A lightweight everyday blouse with an easy, feminine silhouette.','["M","L","XL"]','["Cream","Black"]',24,true,true),
('Oversized Floral Dress','oversized-floral-dress','Dresses',42000,null,'NEW','https://images.unsplash.com/photo-1554412933-514a83d2f3c8?q=85&w=900&auto=format&fit=crop','Relaxed floral styling with an oversized fit for effortless movement.','["L","XL","2XL","3XL"]','["Floral"]',18,true,true),
('Classic Midi Dress','classic-midi-dress','Dresses',39000,45000,'20% OFF','https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=85&w=900&auto=format&fit=crop','A versatile midi dress that moves easily from day to evening.','["S","M","L","XL"]','["Black","Beige"]',12,true,false),
('Minimal Knit Top','minimal-knit-top','Top & Blouse',25000,null,'BEST','https://images.unsplash.com/photo-1485968579580-b6d095142e6e?q=85&w=900&auto=format&fit=crop','Clean lines and a soft knit feel make this an easy wardrobe staple.','["M","L","XL"]','["Oat","Black"]',30,true,true),
('Wide Leg Trouser','wide-leg-trouser','Pants',35000,null,'','https://images.unsplash.com/photo-1506629905607-d9a5d1f2a1f1?q=85&w=900&auto=format&fit=crop','A flattering wide-leg trouser made for polished everyday outfits.','["M","L","XL","2XL"]','["Black","Cream"]',16,true,false),
('Plus Size Soft Dress','plus-size-soft-dress','Plus Size',46000,52000,'SALE','https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=85&w=900&auto=format&fit=crop','A soft, flattering plus-size dress designed for comfort and confidence.','["XL","2XL","3XL","4XL"]','["Rose","Black"]',14,true,true),
('Pleated Day Skirt','pleated-day-skirt','Skirt',30000,null,'NEW','https://images.unsplash.com/photo-1583496661160-fb5886a13d27?q=85&w=900&auto=format&fit=crop','An easy pleated skirt for simple everyday styling.','["S","M","L","XL"]','["Cream","Black"]',15,true,false),
('Soft Cozy Cardigan','soft-cozy-cardigan','Cozy & Outerwear',38000,null,'','https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=85&w=900&auto=format&fit=crop','A soft layering piece for cool evenings and relaxed looks.','["M","L","XL","2XL"]','["Oat","Mocha"]',10,true,false),
('Relaxed Cotton Set','relaxed-cotton-set','Set & Suit',44000,50000,'SALE','https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?q=85&w=900&auto=format&fit=crop','Matching top and trouser set for an effortless polished look.','["M","L","XL","2XL"]','["Black","Stone"]',9,true,false),
('Everyday Blazer Set','everyday-blazer-set','Set & Suit',58000,null,'BEST','https://images.unsplash.com/photo-1591369822096-ffd140ec948f?q=85&w=900&auto=format&fit=crop','A smart coordinated set for work, events and elevated everyday wear.','["M","L","XL"]','["Black","Beige"]',8,true,false),
('Classic Basic Tee','classic-basic-tee','Other',18000,null,'','https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=85&w=900&auto=format&fit=crop','A clean everyday basic that pairs with everything.','["S","M","L","XL"]','["White","Black"]',35,true,false)
on conflict(slug) do nothing;

-- After running this file, create the admin account in Supabase Auth
-- (Authentication -> Users -> Add user), then add that user's UUID to admin_users:
-- insert into public.admin_users(id,email) values('AUTH_USER_UUID','admin@example.com');
