-- Lu's Collections: admin enhancements migration
-- Run this once in Supabase SQL Editor. Safe to re-run.

-- Support multiple photos per product while keeping the existing `image` primary image.
alter table public.products add column if not exists images text[] not null default '{}';
update public.products set images = array[image] where coalesce(array_length(images,1),0)=0 and coalesce(image,'')<>'';

-- OOTD posts managed from /admin/.
create table if not exists public.ootd_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  caption text not null default '',
  image_url text not null,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_ootd_posts_active_sort on public.ootd_posts(is_active,sort_order,created_at desc);
alter table public.ootd_posts enable row level security;
drop policy if exists "public read active ootd posts" on public.ootd_posts;
create policy "public read active ootd posts" on public.ootd_posts for select to anon,authenticated using (is_active=true or (select public.is_admin()));
drop policy if exists "admins insert ootd posts" on public.ootd_posts;
create policy "admins insert ootd posts" on public.ootd_posts for insert to authenticated with check ((select public.is_admin()));
drop policy if exists "admins update ootd posts" on public.ootd_posts;
create policy "admins update ootd posts" on public.ootd_posts for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));
drop policy if exists "admins delete ootd posts" on public.ootd_posts;
create policy "admins delete ootd posts" on public.ootd_posts for delete to authenticated using ((select public.is_admin()));
grant select on public.ootd_posts to anon,authenticated;
grant insert,update,delete on public.ootd_posts to authenticated;
grant usage,select on sequence public.ootd_posts_id_seq to authenticated;

-- Ensure the announcement bar has a default text, but preserve any existing value.
insert into public.settings(key,value) values
('announcement_text','✦ အမှာစာ ၅၀,၀၀၀ ကျပ်နှင့်အထက် ပို့ခအခမဲ့ • NEW ARRIVALS — 20% OFF • Premium everyday wear • Plus Size available')
on conflict(key) do nothing;

-- The bucket already exists in the original setup. Ensure admin upload/update/delete rules exist.
insert into storage.buckets(id,name,public) values('product-images','product-images',true)
on conflict(id) do update set public=true;
drop policy if exists "admins upload product images" on storage.objects;
create policy "admins upload product images" on storage.objects for insert to authenticated with check(bucket_id='product-images' and (select public.is_admin()));
drop policy if exists "admins update product images" on storage.objects;
create policy "admins update product images" on storage.objects for update to authenticated using(bucket_id='product-images' and (select public.is_admin())) with check(bucket_id='product-images' and (select public.is_admin()));
drop policy if exists "admins delete product images" on storage.objects;
create policy "admins delete product images" on storage.objects for delete to authenticated using(bucket_id='product-images' and (select public.is_admin()));
